language: android 
sudo: false
addons:
  apt:
    packages:
      - imagemagick
android:
  update_sdk: true
  components:
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
    - $ANDROID_HOME
before_cache:
  - find $HOME/.gradle -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - find $HOME/.android -name *.lock -print | xargs -I {} -P 4 rm -rf {}

env:
- QUALITY=50

before_install:
- cp -rf tools/licenses $ANDROID_HOME

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-222DIY/archive/local.zip
- unzip -q ygopro-222DIY-local.zip
- cp -rf ygopro-222DIY-local/ocgcore Classes

    - mkdir script
    - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-pre-script/archive/master.zip
    - 7z x ygopro-pre-script-master.zip
    - cp -rf ygopro-pre-script-master/scripts/**/*.lua script
    - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/archive/master.zip
    - 7z x ygopro-scripts-master.zip
    - cp -rf ygopro-scripts-master/*.lua script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/ygopro222-images/archive/master.zip
- unzip -q ygopro222-images-master.zip
- mv -f ygopro222-images-master pics


- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
- mv -f strings.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/cards.cdb
- mv -f cards.cdb mobile/assets/data

- mkdir mobile/assets/data/expansions

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-222DIY/archive/data.zip
- unzip -q ygopro-222DIY-data.zip
- cp -rf ygopro-222DIY-data/expansions/pics .
- cp -rf ygopro-222DIY-data/expansions/script .
- cp -rf ygopro-222DIY-data/expansions/*.cdb mobile/assets/data/expansions
- cp -rf ygopro-222DIY-data/expansions/strings.conf mobile/assets/data/expansions
- cp -rf ygopro-222DIY-data/lflist.conf mobile/assets/data/conf

- rm -rf pics/thumbnail
- rm -rf pics/*.db
- cd pics && ls *.jpg | xargs -I {} -P 4 convert -size 177x254! -quality $QUALITY {} {} && cd ..

- zip -q -r mobile/assets/data/pics.zip pics
- zip -q -r mobile/assets/data/scripts.zip script

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore && ./../android-ndk-r15b/ndk-build -j8 && cd ..
- ./gradlew :mobile:assembleMycardRelease

before_deploy:
  - mkdir op
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk op/ygomobile-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.apk

deploy:
  provider: releases
  api-key: $NANAHIRA
  file: op/ygomobile-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.apk
  skip_cleanup: true
  on:
    tags: true
